version: '2.1'

volumes:
    wp-db:
      driver: local
    wp:
      driver: local

services:
  wpdb:
    image: mysql:5.7.26
    container_name: wpdb
    env_file: .env
    restart: always
    volumes:
         - wp-db:/var/lib/mysql

  wordpress:
    image: trydirect/wordpress:5_0_3
    build: build/wordpress
    container_name: wordpress
    restart: always
    env_file: .env
    links:
      - wpdb:db
    volumes:
      - wp:/var/www/html/WordPress-5.0.3
      - ./configs/supervisord/wordpress.conf:/etc/supervisord.conf
      - ./configs/wordpress/wp-config.php:/var/www/html/Word Press-5.0.3/wp-config.php
      - ./configs/php/php.ini:/etc/php/7.0/fpm/php.ini
    ports:
      - "9000"
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n

  # entry point
  nginx:
    image: trydirect/nginx:latest
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    ports:
      - "80:80"
    links:
      - wordpress
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/supervisord/nginx.conf:/etc/supervisor/conf.d/nginx.conf
      - ./configs/cron/nginx:/var/spool/cron/crontabs
      - wp:/usr/share/nginx/www
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n
